# Base image
FROM python:3.9-slim

# Create working directory in container
WORKDIR /app

# Copy requirements file to wd
COPY requirements_main.txt .

# Install libraries
RUN pip install -r requirements_main.txt

# Copy folders & files to run pipeline: config, src, pipeline.py
COPY config ./config
COPY src ./src
COPY pipeline.py .

# Command to run when running docker container
CMD ["python", "pipeline.py"]