path:
  image_path: 04_Implementation/model_endpoint/plane.jpg
  flask_url: http://3.22.68.161:5000/predict

message:
  header: How much do I need to pay for the flight?
  airline_input: What's the airline?
  seat_input: Which seat do you want?
  depart_time_input: What time do you depart?
  origin_input: What's your origin?
  destination_input: What's your destination?
  stop_input: How many stops do you have?
  model_input: Which model do you want to use?

inputs:
  airline:
    - Air India
    - AirAsia
    - GO FIRST
    - Indigo
    - Spicejet
    - Vistra
  depart_time:
    - early_morning
    - morning
    - afternoon
    - evening
    - night
    - late_night
  origin:
    - Bangalore
    - Chennai
    - Delhi
    - Hyderbad
    - Kolkata
    - Mumbai
  destination:
    - Bangalore
    - Chennai
    - Delhi
    - Hyderbad
    - Kolkata
    - Mumbai

aws:
  bucket_name: msia423-g7
  prefix: experiments