name: Python Unit Tests

on:
  push:
    paths:
      - '04_Implementation/**'
    branches:
      - main
  pull_request:
    paths:
      - '04_Implementation/**'
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest # define type of initial machine

    defaults:
      run:
        working-directory: 04_Implementation
    steps:
      - name: Checkout code
        uses: actions/checkout@v3 

      - name: Set up Python # setup python 3.9
        uses: actions/setup-python@v3
        with:
          python-version: 3.9

      - name: Install dependencies # install dependencies in the virtual machine 
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements_main.txt

      - name: Run tests # run tests on test folderP
        run: python3 -m pytest
      
      - name: Run code coverage
        run: python3 -m pytest --cov tests
